on:
  schedule: 
    - cron: '0 * * * *'

name: Update ICU Report

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
        contents: write
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0' # The R version to download (if necessary) and use.
 
      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "dplyr", "tidyr", "ggplot2", "readr", "tidyverse", "googledrive"), repos="http://cran.us.r-project.org")'


      - name: Update ICU Report
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: Assignment-7.qmd

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit
        run: |
          git add .
          git commit -m "Updated report"
          git push origin main

